name: Build
on:
  workflow_dispatch:
    inputs:
      versionTag:
        description: 'Lemminx Version Tag'
        required: true
        type: string
jobs:
  build-binary-unix:
    runs-on: ${{ matrix.os }}
    env:
      GRAALVM_DISTRO: graalvm
      GRAALVM_JAVA: 17
    strategy:
      fail-fast: true
      matrix:
        include:
          - os: macos-latest
            label: 'darwin-x64'
          - os: macos-14
            label: 'darwin-arm64'
          - os: ubuntu-20.04
            label: 'linux'
    steps:
    - uses: actions/checkout@v4
      with:
        repository: 'eclipse/lemminx'
        ref: ${{ inputs.versionTag }}
    - name: Cache Maven dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.m2/repository
          ~/.m2/wrapper
          !~/.m2/repository/org/eclipse/lemminx
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Cache GraalVM
      uses: actions/cache@v4
      with:
        path: |
          /opt/hostedtoolcache/graalvm-jdk-*
          ~/hostedtoolcache/graalvm-jdk-*
        key: ${{ runner.os }}-graalvm-jdk-${{ env.GRAALVM_JAVA }}
        restore-keys: |
          ${{ runner.os }}-graalvm-jdk-
    - uses: graalvm/setup-graalvm@a1b47fdf04e772fed6b3b46131e226f9aea5e169 #v1.1.6
      with:
        distribution: ${{env.GRAALVM_DISTRO}}
        java-version: ${{env.GRAALVM_JAVA}}
    - run: ./mvnw -B package -Dnative -DskipTests $([ $(uname -s) = Linux ] && echo "-Dgraalvm.static=-H:+StaticExecutableWithDynamicLibC") -Dcbi.jarsigner.skip=true
    - run: mv org.eclipse.lemminx/target/lemminx-* lemminx-${{ matrix.label }}
    - uses: actions/upload-artifact@v4
      with:
        name: lemminx-${{ matrix.label }}
        path: lemminx-${{ matrix.label }}
        if-no-files-found: error
  build-binary-windows:
    runs-on: windows-latest
    env:
      GRAALVM_DISTRO: graalvm
      GRAALVM_JAVA: 17
    steps:
    - name: Check out LemMinX
      uses: actions/checkout@v4
      with:
        repository: 'eclipse/lemminx'
        ref: ${{ inputs.versionTag }}
    - name: Cache Maven dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.m2/repository
          ~/.m2/wrapper
          !~/.m2/repository/org/eclipse/lemminx
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Cache GraalVM
      uses: actions/cache@v4
      with:
        path: |
          C:\hostedtoolcache\windows\graalvm-ce-*
        key: ${{ runner.os }}-graalvm-*
        restore-keys: |
          ${{ runner.os }}-graalvm-
    - uses: ilammy/msvc-dev-cmd@7315a94840631165970262a99c72cfb48a65d25d #v1.12.0
    - uses: graalvm/setup-graalvm@a1b47fdf04e772fed6b3b46131e226f9aea5e169 #v1.1.6
      with:
        distribution: ${{env.GRAALVM_DISTRO}}
        java-version: ${{env.GRAALVM_JAVA}}
    - run: .\mvnw.cmd -B package -Dnative -DskipTests -D "cbi.jarsigner.skip=true"
    - run: mv org.eclipse.lemminx\target\lemminx-*.exe lemminx-win32.exe
    - uses: actions/upload-artifact@v4
      with:
        name: lemminx-win32
        path: lemminx-win32.exe
        if-no-files-found: error
